version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=health-horse-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
